import type { Component } from 'svelte';
import { 
  Activity, ArrowDown, ArrowUp, ArrowUpDown, Bell, BookOpen,
  ChartColumn, ChartColumnBig, ChartLine, Check, ChevronDown,
  ChevronLeft, ChevronRight, CircleCheck, Clipboard, ClipboardCheck,
  ClipboardList, Cog, Copy, DollarSign, Eye, EyeOff, FileText,
  Flag, FolderKanban, GitBranch, Globe, Home, Inbox, LayoutDashboard,
  Link, List, Loader, Lock, LogOut, MapPin, Menu, Plus, RefreshCw,
  Scale, Search, Server, Settings, Shield, ShieldCheck, Siren,
  SlidersHorizontal, SquareCheck, TrendingDown, TrendingUp,
  TriangleAlert, User, Users, X, Zap
} from '@lucide/svelte';

export const lucideIconMap: Record<string, Component> = {
  'activity': Activity,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  'arrow-up-down': ArrowUpDown,
  'bar-chart-2': ChartColumn,
  'bar-chart-3': ChartColumnBig,
  'bell': Bell,
  'book-open': BookOpen,
  'check': Check,
  'check-circle': CircleCheck,
  'check-square': SquareCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'clipboard': Clipboard,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'cog': Cog,
  'copy': Copy,
  'dollar-sign': DollarSign,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  'flag': Flag,
  'folder-kanban': FolderKanban,
  'git-branch': GitBranch,
  'globe': Globe,
  'home': Home,
  'inbox': Inbox,
  'layout-dashboard': LayoutDashboard,
  'line-chart': ChartLine,
  'link': Link,
  'list': List,
  'loader': Loader,
  'lock': Lock,
  'log-out': LogOut,
  'map-pin': MapPin,
  'menu': Menu,
  'plus': Plus,
  'refresh-cw': RefreshCw,
  'scale': Scale,
  'search': Search,
  'server': Server,
  'settings': Settings,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'siren': Siren,
  'sliders': SlidersHorizontal,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'user': User,
  'users': Users,
  'x': X,
  'zap': Zap,
};
